FROM golang:alpine AS builder
WORKDIR /depeche-auth
COPY  . .
RUN apk update
RUN CGO_ENABLED=0 GOOS=linux go build -o main -ldflags="-s -w" -a -installsuffix cgo ./authorization_ms/cmd/main.go

FROM alpine
WORKDIR /depeche-auth
COPY --from=builder ./depeche-auth .

EXPOSE 8081


ENTRYPOINT ["./main"]