version: "3.9"
services:
  backend:
    container_name: depeche_backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - "postgres:postgres"
      - "auth:auth"
    depends_on:
      postgres:
        condition: service_started
      static:
        condition: service_started

  redis:
    image: redis:latest
    container_name: depeche_redis
    env_file:
      - .env
    ports:
      - "6379:6379"
    command: >
      --requirepass ${REDIS_PASS}

  postgres:
    image: postgres:15-alpine
    container_name: depeche_postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always

  auth:
    container_name: depeche_auth_ms
    build:
      context: ./
      dockerfile: Dockerfile-auth
    ports:
      - "8081:8081"
      - "8091:8091"
    links:
      - "redis:redis"
    depends_on:
      redis:
        condition: service_started


  static:
    container_name: depeche_static
    build:
      context: ./
      dockerfile: Dockerfile-static
    links:
      - "auth:auth"
    ports:
      - "8082:8082"
      - "8092:8092"
      - "8182:8182"

    volumes:
      - ./static/files/sticker:/depeche-static/static/files/sticker
      - static_files:/depeche-static/static

volumes:
  db_data:
  static_files:
