FROM golang:alpine AS builder
WORKDIR /depeche-static
COPY  . .
RUN apk update
RUN CGO_ENABLED=0 GOOS=linux go build -o main -ldflags="-s -w" -a -installsuffix cgo ./static/cmd/app/main.go

FROM alpine
WORKDIR /depeche-static
COPY --from=builder ./depeche-static .

RUN mkdir "static/files"
RUN mkdir "static/files/img"
RUN mkdir "static/files/doc"
RUN mkdir "static/files/sticker"

EXPOSE 8082


ENTRYPOINT ["./main"]