version: "3.8"
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env/postgres
      - .env/backend

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env/postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql

    healthcheck:
      test : ["CMD-SHELL", "pg_isready -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always

volumes:
  db_data: