version: "3.9"

services:
  prometheus:
    image: prom/prometheus
    container_name: depeche_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./metrics_config:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  nodeexporter:
    image: prom/node-exporter
    container_name: depeche_node_exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
    ports:
      - "9100:9100"

  grafana:
    image: grafana/grafana-enterprise
    container_name: depeche_grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    user: ":"
    volumes:
      - ./data/grafana:/var/lib/grafana