version: "3.9"
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_started
  redis:
    image: redis:alpine
    container_name: dpredis
    ports:
      - "6379:6379"
    command:
     - --requirepass ${REDIS_PASS}
