version: "3.9"
services:
  backend:
    container_name: depeche_backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - "postgres:postgres"
      - "auth:auth"
    depends_on:
      postgres:
        condition: service_started
      static:
        condition: service_started
    networks:
      my_network:
        ipv4_address: 172.28.0.0

  redis:
    image: redis:latest
    container_name: depeche_redis
    env_file:
      - .env
    ports:
      - "6379:6379"
    command: >
      --requirepass ${REDIS_PASS}
    networks:
      my_network:
        ipv4_address: 172.28.0.1

  postgres:
    image: postgres:15-alpine
    container_name: depeche_postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    command:
      - "postgres"
      - "-c"
      - "log_statement=all"
      - "-c"
      - "config_file=/etc/postgresql/postgres.conf"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - ./configs/pg:/etc/postgresql
      - ./log/postgresql:/var/lib/postgresql/log

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    networks:
      my_network:
        ipv4_address: 172.28.0.2

  auth:
    container_name: depeche_auth_ms
    build:
      context: ./
      dockerfile: Dockerfile-auth
    ports:
      - "8081:8081"
      - "8091:8091"
    links:
      - "redis:redis"
    depends_on:
      redis:
        condition: service_started
    networks:
      my_network:
        ipv4_address: 172.28.0.3


  static:
    container_name: depeche_static
    build:
      context: ./
      dockerfile: Dockerfile-static
    links:
      - "auth:auth"
    ports:
      - "8082:8082"
      - "8092:8092"
      - "8182:8182"

    volumes:
      - ./static/files/sticker:/depeche-static/static/files/sticker
      - static_files:/depeche-static/static
    networks:
      my_network:
        ipv4_address: 172.28.0.4

volumes:
  db_data:
  static_files:


networks:
  my_network:
    name: seekers_network
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.4