// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: csrf.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CSRF struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *CSRF) Reset() {
	*x = CSRF{}
	if protoimpl.UnsafeEnabled {
		mi := &file_csrf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSRF) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSRF) ProtoMessage() {}

func (x *CSRF) ProtoReflect() protoreflect.Message {
	mi := &file_csrf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSRF.ProtoReflect.Descriptor instead.
func (*CSRF) Descriptor() ([]byte, []int) {
	return file_csrf_proto_rawDescGZIP(), []int{0}
}

func (x *CSRF) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CSRF) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type TokenCSRF struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *TokenCSRF) Reset() {
	*x = TokenCSRF{}
	if protoimpl.UnsafeEnabled {
		mi := &file_csrf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenCSRF) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenCSRF) ProtoMessage() {}

func (x *TokenCSRF) ProtoReflect() protoreflect.Message {
	mi := &file_csrf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenCSRF.ProtoReflect.Descriptor instead.
func (*TokenCSRF) Descriptor() ([]byte, []int) {
	return file_csrf_proto_rawDescGZIP(), []int{1}
}

func (x *TokenCSRF) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type EmailCSRF struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *EmailCSRF) Reset() {
	*x = EmailCSRF{}
	if protoimpl.UnsafeEnabled {
		mi := &file_csrf_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmailCSRF) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailCSRF) ProtoMessage() {}

func (x *EmailCSRF) ProtoReflect() protoreflect.Message {
	mi := &file_csrf_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailCSRF.ProtoReflect.Descriptor instead.
func (*EmailCSRF) Descriptor() ([]byte, []int) {
	return file_csrf_proto_rawDescGZIP(), []int{2}
}

func (x *EmailCSRF) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type Valid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Valid bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *Valid) Reset() {
	*x = Valid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_csrf_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Valid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Valid) ProtoMessage() {}

func (x *Valid) ProtoReflect() protoreflect.Message {
	mi := &file_csrf_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Valid.ProtoReflect.Descriptor instead.
func (*Valid) Descriptor() ([]byte, []int) {
	return file_csrf_proto_rawDescGZIP(), []int{3}
}

func (x *Valid) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

var File_csrf_proto protoreflect.FileDescriptor

var file_csrf_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x63, 0x73, 0x72, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x73,
	0x72, 0x66, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x32, 0x0a, 0x04, 0x43, 0x53, 0x52, 0x46, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x22, 0x21, 0x0a, 0x09, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x43, 0x53, 0x52, 0x46,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x21, 0x0a, 0x09, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x43,
	0x53, 0x52, 0x46, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x1d, 0x0a, 0x05, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x32, 0xab, 0x01, 0x0a, 0x0b, 0x43, 0x53, 0x52,
	0x46, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x33, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x43, 0x53, 0x52, 0x46, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x0f, 0x2e, 0x63, 0x73,
	0x72, 0x66, 0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x43, 0x53, 0x52, 0x46, 0x1a, 0x0f, 0x2e, 0x63,
	0x73, 0x72, 0x66, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x43, 0x53, 0x52, 0x46, 0x12, 0x39, 0x0a,
	0x13, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x43, 0x53, 0x52, 0x46, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x0a, 0x2e, 0x63, 0x73, 0x72, 0x66, 0x2e, 0x43, 0x53, 0x52, 0x46,
	0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x2c, 0x0a, 0x11, 0x56, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x43, 0x53, 0x52, 0x46, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x0a, 0x2e,
	0x63, 0x73, 0x72, 0x66, 0x2e, 0x43, 0x53, 0x52, 0x46, 0x1a, 0x0b, 0x2e, 0x63, 0x73, 0x72, 0x66,
	0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x3b, 0x61, 0x70, 0x69,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_csrf_proto_rawDescOnce sync.Once
	file_csrf_proto_rawDescData = file_csrf_proto_rawDesc
)

func file_csrf_proto_rawDescGZIP() []byte {
	file_csrf_proto_rawDescOnce.Do(func() {
		file_csrf_proto_rawDescData = protoimpl.X.CompressGZIP(file_csrf_proto_rawDescData)
	})
	return file_csrf_proto_rawDescData
}

var file_csrf_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_csrf_proto_goTypes = []interface{}{
	(*CSRF)(nil),          // 0: csrf.CSRF
	(*TokenCSRF)(nil),     // 1: csrf.TokenCSRF
	(*EmailCSRF)(nil),     // 2: csrf.EmailCSRF
	(*Valid)(nil),         // 3: csrf.Valid
	(*emptypb.Empty)(nil), // 4: google.protobuf.Empty
}
var file_csrf_proto_depIdxs = []int32{
	2, // 0: csrf.CSRFService.CreateCSRFToken:input_type -> csrf.EmailCSRF
	0, // 1: csrf.CSRFService.InvalidateCSRFToken:input_type -> csrf.CSRF
	0, // 2: csrf.CSRFService.ValidateCSRFToken:input_type -> csrf.CSRF
	1, // 3: csrf.CSRFService.CreateCSRFToken:output_type -> csrf.TokenCSRF
	4, // 4: csrf.CSRFService.InvalidateCSRFToken:output_type -> google.protobuf.Empty
	3, // 5: csrf.CSRFService.ValidateCSRFToken:output_type -> csrf.Valid
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_csrf_proto_init() }
func file_csrf_proto_init() {
	if File_csrf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_csrf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSRF); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_csrf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenCSRF); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_csrf_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmailCSRF); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_csrf_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Valid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_csrf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_csrf_proto_goTypes,
		DependencyIndexes: file_csrf_proto_depIdxs,
		MessageInfos:      file_csrf_proto_msgTypes,
	}.Build()
	File_csrf_proto = out.File
	file_csrf_proto_rawDesc = nil
	file_csrf_proto_goTypes = nil
	file_csrf_proto_depIdxs = nil
}
