host: ""
port: 8080
session:
  host: "redis"
  port: 6379
  db: 0
db:
  host: "postgres"
  user: "depeche"
  port: 5432
  database: "depeche_db"
auth_ms:
  host: "auth"
  port: 8081
static_ms:
  host: "static"
  port: 8082
  color_port: 8182

#host: ""
#port: 8080
#session:
#  host: "localhost"
#  port: 6379
#  db: 0
#db:
#  host: "localhost"
#  port: 5432
#  database: "depeche_db"
#auth_ms:
#  host: "localhost"
#  port: 8081
#static_ms:
#  host: "localhost"
#  port: 8082
#  color_port: 8182
