// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "CashMap team"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/feed": {
            "get": {
                "description": "Get users's new feed part by last post id and batch size.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "feed"
                ],
                "summary": "Get feed part",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Posts amount",
                        "name": "batch_size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date and time of last post given. If not specified the newest posts will be sent",
                        "name": "last_post_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.Post"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/api/posts/community": {
            "get": {
                "description": "User can get community's posts in includes batches older than specified in \"last_post_date\"",
                "tags": [
                    "Post"
                ],
                "summary": "Get post by community link",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of the community on whose wall the post is located",
                        "name": "community_link",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Posts amount",
                        "name": "batch_size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date and time of last post given. If not specified the newest posts will be sent",
                        "name": "last_post_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/doc.PostsResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/api/posts/create": {
            "post": {
                "description": "User can create new post",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Post"
                ],
                "summary": "Create new post",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/doc.PostsResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/api/posts/delete": {
            "delete": {
                "description": "User can delete post",
                "tags": [
                    "Post"
                ],
                "summary": "Delete post by id",
                "parameters": [
                    {
                        "description": "Post to delete info",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/doc.PostDelete"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/api/posts/edit": {
            "patch": {
                "description": "User can edit post",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Post"
                ],
                "summary": "Edit post by id",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/api/posts/id": {
            "get": {
                "description": "User can get post by id, returned by server from CreatePost handler",
                "tags": [
                    "Post"
                ],
                "summary": "Get post by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Post ID",
                        "name": "post_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Posts amount",
                        "name": "batch_size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date and time of last post given. If not specified the newest posts will be sent",
                        "name": "last_post_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/doc.PostResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/api/posts/profile": {
            "get": {
                "description": "User can get user's posts in includes batches older than specified in \"last_post_date\"",
                "tags": [
                    "Post"
                ],
                "summary": "Get post by user link",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of the user on whose wall the post is located",
                        "name": "owner_link",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Posts amount",
                        "name": "batch_size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date and time of last post given. If not specified the newest posts will be sent",
                        "name": "last_post_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/doc.PostsResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/api/static/delete": {
            "delete": {
                "description": "Users can delete file on server",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "static"
                ],
                "summary": "Delete file from server",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "File type (",
                        "name": "type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/api/static/download": {
            "get": {
                "description": "Users can read file on server",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "static"
                ],
                "summary": "Read file from server",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "File type (",
                        "name": "type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/api/static/upload": {
            "post": {
                "description": "Users can upload many files using multipart/form-data",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "static"
                ],
                "summary": "Load file on server",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.UserFile"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "413": {
                        "description": "Request Entity Too Large"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Delete user session and invalidate session cookie",
                "tags": [
                    "auth"
                ],
                "summary": "Log out",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/auth/sign-in": {
            "post": {
                "description": "Authorize client with credentials (login and password).",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Sign in",
                "parameters": [
                    {
                        "description": "User login",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "User password",
                        "name": "password",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/auth/sign-up": {
            "post": {
                "description": "Register client with credentials and other user info.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Sign up",
                "parameters": [
                    {
                        "description": "User email",
                        "name": "email",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "User password",
                        "name": "password",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "User first name",
                        "name": "first_name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "User last name",
                        "name": "last_name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "doc.PostDelete": {
            "description": "All post information",
            "type": "object",
            "properties": {
                "body": {
                    "$ref": "#/definitions/dto.PostDelete"
                }
            }
        },
        "doc.PostResponse": {
            "description": "All post information",
            "type": "object",
            "properties": {
                "body": {
                    "$ref": "#/definitions/entities.Post"
                }
            }
        },
        "doc.PostsResponse": {
            "description": "All post information",
            "type": "object",
            "properties": {
                "body": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Post"
                    }
                }
            }
        },
        "dto.PostCreate": {
            "type": "object",
            "properties": {
                "author_link": {
                    "type": "string"
                },
                "community_link": {
                    "type": "string"
                },
                "owner_link": {
                    "type": "string"
                },
                "show_author": {
                    "type": "boolean"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "dto.PostDelete": {
            "type": "object",
            "properties": {
                "post_id": {
                    "type": "integer"
                }
            }
        },
        "dto.PostUpdate": {
            "type": "object",
            "properties": {
                "post_id": {
                    "type": "integer"
                },
                "show_author": {
                    "type": "boolean"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "entities.FileType": {
            "type": "string",
            "enum": [
                "img",
                "doc"
            ],
            "x-enum-varnames": [
                "IMAGE",
                "DOCUMENT"
            ]
        },
        "entities.Post": {
            "description": "All post information",
            "type": "object",
            "properties": {
                "attachments": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "author_link": {
                    "type": "string"
                },
                "change_date": {
                    "type": "string"
                },
                "community_link": {
                    "type": "string"
                },
                "creation_date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_deleted": {
                    "type": "boolean"
                },
                "likes_amount": {
                    "type": "integer"
                },
                "owner_link": {
                    "type": "string"
                },
                "show_author": {
                    "type": "boolean"
                },
                "text_content": {
                    "type": "string"
                }
            }
        },
        "entities.UserFile": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/entities.FileType"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Depeche API",
	Description:      "Api for Depeche social network. VK Education project. Spring, 2023",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
