name: Depeche CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Run linters
        uses: golangci/golangci-lint-action@v3

      - name: Build
        run : go build ./...

      - name: Run tests
        run :  go test $(go list ./... | grep -v vendor) -race -coverprofile=coverage.out

      - name: Coverage
        run : go tool cover -func=coverage.out
