name: Depeche CI

on:
  push:
    branches: ["main"]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Run linters
        uses: golangci/golangci-lint-action@v3

      - name: Build
        run : go build ./...

      - name: Run tests
        run :  go test $(go list ./... | grep -v vendor) -race -coverprofile=coverage.out

      - name: Coverage
        run : go tool cover -func=coverage.out

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: backend
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: backend
          path: .

      - name: Send files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "./*"
          target: "/home/ubuntu/backend/"

      - name: Docker build
        uses: appleboy/ssh-action@master
        with:
          command_timeout: 30m
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script:  docker build -t 2023_1_CashMap_backend_container; docker run -dp 8080:8080 2023_1_CashMap_backend_container;
